import "./globals.css"
import { Toaster } from "sonner"
import type { Metadata } from "next"
import { Poppins } from "next/font/google"

import { ThemeProvider } from "@/components/providers/theme-provider"

const font = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Kekee Admin",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          storageKey="kekee-admin-theme"
        >
          <Toaster theme="light" position="bottom-center" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
